### ISSUE TITLE
Field types missing

### ISSUE THREAD

**Issue by JOJ0** [adamjakab/BeetsPluginXtractor#25]
As reported here https://github.com/beetbox/beets/discussions/4626, it seems numerical values saved to the beets library via the xtractor plugin can not be used for [range queries](https://beets.readthedocs.io/en/stable/reference/query.html#numeric-range-queries).

The reason supposedly is that xtractor does not define types FOR its values.

A possible fix could be to take the now deprecated acousticbrainz plugin as an example and implement similar field types: https://github.com/beetbox/beets/blob/master/beetsplug/acousticbrainz.py#L113-L136

**Comment by JOJ0** [comment]
Beets developer docs around field types for flexible attributes: https://beets.readthedocs.io/en/stable/dev/plugins.html#flexible-field-types

**Comment by arsaboo** [comment]
@JOJ0 It is relatively straightforward. See the Spotify plugin for example 

https://github.com/beetbox/beets/blob/master/beetsplug/spotify.py#L46-L60

I am traveling right now and can do it after I return. But I am sure, you will be able to finish it before that :)

**Comment by adamjakab** [comment]
Hi both,

Yes, this should be in place and I am actually not sure why it is not. 
I used to use this project in conjunction with this one: https://github.com/adamjakab/BeetsPluginGoingRunning
and I used to do all sorts of numeric / range matching on the extracted values.
So I am not sure what happened but if the type definitions are not there we should consider this a bug.

**Comment by JOJ0** [comment]
> Yes, this should be in place and I am actually not sure why it is not. 

I have an idea why you possibly didn't add types for xtractor back then: The official acousticbrainz plugin is creating some equally named types already, thus redefining them here causes a duplicate error.

I'm about to figure out how I would define those values like I did in https://github.com/adamjakab/BeetsPluginXtractor/pull/26/files already and at the same time, avoid duplication.

Since we recently reconsidered to not entirely delete the soon deprecated acousticbrain/absubmit plugins code (https://github.com/beetbox/beets/pull/4636), the problem doesn't vanish and I need to solve the issue. I was waiting about the outcome of that PR over there to know whether I could merge #26 as-is or it needs further work.

**Comment by JOJ0** [comment]
I finally merged #26 which adds the missing `types`. The acousticbrainz plugin which holds conflicting `types` that would lead to errors as described above, was deprecated in beets a couple of weeks/months ago.

I didn't go down the route of trying to only define those types if they are missing, if someone still has the acousticbrainz plugin enabled for some reason there will be a conflict and they'll hopefully investigate and find this issue. I think that's fine probably not worth the hassle to look into a more robust solution. Most of all a beets user with acousticbrainz plugin enabled will now get warnings all over the place that the plugin they are using is deprecated and has no functionality anymore except for experimental purposes.
