### ISSUE TITLE
Fix setup.py deprecation in pythonpublish gh-actions workflow

### ISSUE THREAD

**Issue by JOJ0** [adamjakab/BeetsPluginXtractor#27]
Fix this deprecation warning in our actions workflow before next release:

```
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

Probably something like that will do:
```
python -m build
```

**Comment by adamjakab** [comment]
@JOJ0 - Done. Built a new pipeline.
If you publish a new version tag (also remember to bump it up in /beetsplug/xtractor/about.py) the GH Action pipeline will be triggered, run the tests, create a new release and deploy on pypi.
