### ISSUE TITLE
Use other methods to keep track of progress

### ISSUE THREAD

**Issue by arsaboo** [adamjakab/BeetsPluginXtractor#29]
Currently, the plugin uses the extracted data files to keep track of progress. For a large library, the data files themselves can take up a lot of space and may not be of much use to most people. Instead, we should use a field to check if the track is already processed. We could define one field (say `danceability` or make it user configurable). If `danceability` exists for a track, we can assume that the track is already processed and skip it. We can allow a force overwrite option to ignore the check. [Spotify](https://beets.readthedocs.io/en/latest/plugins/spotify.html#obtaining-track-popularity-and-audio-features-from-spotify) plugin uses the same approach.

**Comment by JOJ0** [comment]
Does it? Where's that part in the code?

**Comment by arsaboo** [comment]
Here's the part. 

https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beetsplug/spotify.py#L624-L627

If `spotify_track_popularity` is in the `item` and `not force` skip

**Comment by JOJ0** [comment]
Did you try the keep_output option? Actually it should take care of removing output files after use.

**Comment by arsaboo** [comment]
I have `keep_output: yes` and it resumes. The problem is the data files that are left behind, which I don't think are very useful and can be removed. My impression is if I manually delete those output files and `beet xtractor` again, it will process all the files again (even those that are already processed).

**Comment by arsaboo** [comment]
The output files are useful for debugging or for someone looking for additional insights. Most users have no value for them, so we should not assume those files to track progress.

**Comment by JOJ0** [comment]
You don't need to keep the output files to make xtractor properly resume where it left of. Please try setting `keep_output: no`

**Comment by JOJ0** [comment]
> Here's the part.
> 
> https://github.com/beetbox/beets/blob/8fc3ddee2702d0612c5340700f876d78c3e06bbc/beetsplug/spotify.py#L624-L627
> 
> If `spotify_track_popularity` is in the `item` and `not force` skip

You misunderstood, I was not clear enough: I was referring to the statement in your first sentence in the initial post. Where is that part in xtractor's code? What makes you think that progress is _not_ resumed when `keep_output: no` ? Is this a wild guess or do you have evidence that it is that way? How to reproduce that it is not resuming properly if the output files are missing?

**Comment by arsaboo** [comment]
Looks like I just assumed that the output files are required to resume. Closing this...apologies for the confusion.

**Comment by JOJ0** [comment]
No worries, all good :-)
